import torch
from torch.utils.data import DataLoader, SubsetRandomSampler
from tqdm import tqdm
from dataloader.dataloader import IcesfpDataset
import os


def get_dataloader(root_dir, augs_train, batch_size, num_workers, pin_memory):
    dataset_icebird1 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceBird1_restructured/I-0', i45_dir=root_dir + '/icedataset/IceBird1_restructured/I-45', i90_dir=root_dir + '/icedataset/IceBird1_restructured/I-90', i135_dir=root_dir + '/icedataset/IceBird1_restructured/I-135', s0_dir=root_dir + '/icedataset/IceBird1_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceBird1_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceBird1_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceBird1_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceBird1_restructured/masks', label_dir=root_dir + '/icedataset/IceBird1_restructured/normals-png', transform=augs_train)
    dataset_icerabbit1 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceRabbit1_restructured/I-0', i45_dir=root_dir + '/icedataset/IceRabbit1_restructured/I-45', i90_dir=root_dir + '/icedataset/IceRabbit1_restructured/I-90', i135_dir=root_dir + '/icedataset/IceRabbit1_restructured/I-135', s0_dir=root_dir + '/icedataset/IceRabbit1_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceRabbit1_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceRabbit1_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceRabbit1_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceRabbit1_restructured/masks', label_dir=root_dir + '/icedataset/IceRabbit1_restructured/normals-png', transform=augs_train)
    dataset_icepixiu = IcesfpDataset(i0_dir=root_dir + '/icedataset/IcePixiu_restructured/I-0', i45_dir=root_dir + '/icedataset/IcePixiu_restructured/I-45', i90_dir=root_dir + '/icedataset/IcePixiu_restructured/I-90', i135_dir=root_dir + '/icedataset/IcePixiu_restructured/I-135', s0_dir=root_dir + '/icedataset/IcePixiu_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IcePixiu_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IcePixiu_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IcePixiu_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IcePixiu_restructured/masks', label_dir=root_dir + '/icedataset/IcePixiu_restructured/normals-png', transform=augs_train)
    dataset_icebird2 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceBird2_restructured/I-0', i45_dir=root_dir + '/icedataset/IceBird2_restructured/I-45', i90_dir=root_dir + '/icedataset/IceBird2_restructured/I-90', i135_dir=root_dir + '/icedataset/IceBird2_restructured/I-135', s0_dir=root_dir + '/icedataset/IceBird2_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceBird2_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceBird2_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceBird2_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceBird2_restructured/masks', label_dir=root_dir + '/icedataset/IceBird2_restructured/normals-png', transform=augs_train)
    dataset_icetiger = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceTiger_restructured/I-0', i45_dir=root_dir + '/icedataset/IceTiger_restructured/I-45', i90_dir=root_dir + '/icedataset/IceTiger_restructured/I-90', i135_dir=root_dir + '/icedataset/IceTiger_restructured/I-135', s0_dir=root_dir + '/icedataset/IceTiger_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceTiger_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceTiger_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceTiger_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceTiger_restructured/masks', label_dir=root_dir + '/icedataset/IceTiger_restructured/normals-png', transform=augs_train)
    dataset_icecloud = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceCloud_restructured/I-0', i45_dir=root_dir + '/icedataset/IceCloud_restructured/I-45', i90_dir=root_dir + '/icedataset/IceCloud_restructured/I-90', i135_dir=root_dir + '/icedataset/IceCloud_restructured/I-135', s0_dir=root_dir + '/icedataset/IceCloud_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceCloud_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceCloud_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceCloud_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceCloud_restructured/masks', label_dir=root_dir + '/icedataset/IceCloud_restructured/normals-png', transform=augs_train)
    dataset_icepixiu2 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IcePixiu2_restructured/I-0', i45_dir=root_dir + '/icedataset/IcePixiu2_restructured/I-45', i90_dir=root_dir + '/icedataset/IcePixiu2_restructured/I-90', i135_dir=root_dir + '/icedataset/IcePixiu2_restructured/I-135', s0_dir=root_dir + '/icedataset/IcePixiu2_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IcePixiu2_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IcePixiu2_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IcePixiu2_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IcePixiu2_restructured/masks', label_dir=root_dir + '/icedataset/IcePixiu2_restructured/normals-png', transform=augs_train)
    dataset_icebonze = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceBonze_restructured/I-0', i45_dir=root_dir + '/icedataset/IceBonze_restructured/I-45', i90_dir=root_dir + '/icedataset/IceBonze_restructured/I-90', i135_dir=root_dir + '/icedataset/IceBonze_restructured/I-135', s0_dir=root_dir + '/icedataset/IceBonze_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceBonze_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceBonze_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceBonze_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceBonze_restructured/masks', label_dir=root_dir + '/icedataset/IceBonze_restructured/normals-png', transform=augs_train)
    dataset_icebird3 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceBird3_restructured/I-0', i45_dir=root_dir + '/icedataset/IceBird3_restructured/I-45', i90_dir=root_dir + '/icedataset/IceBird3_restructured/I-90', i135_dir=root_dir + '/icedataset/IceBird3_restructured/I-135', s0_dir=root_dir + '/icedataset/IceBird3_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceBird3_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceBird3_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceBird3_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceBird3_restructured/masks', label_dir=root_dir + '/icedataset/IceBird3_restructured/normals-png', transform=augs_train)
    dataset_SunshineDoll = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/I-0', i45_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/I-45', i90_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/I-90', i135_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/I-135', s0_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/masks', label_dir=root_dir + '/icedataset/IceSunshineDoll_restructured/normals-png', transform=augs_train)
    dataset_Mount = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceMount_restructured/I-0', i45_dir=root_dir + '/icedataset/IceMount_restructured/I-45', i90_dir=root_dir + '/icedataset/IceMount_restructured/I-90', i135_dir=root_dir + '/icedataset/IceMount_restructured/I-135', s0_dir=root_dir + '/icedataset/IceMount_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceMount_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceMount_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceMount_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceMount_restructured/masks', label_dir=root_dir + '/icedataset/IceMount_restructured/normals-png', transform=augs_train)
    dataset_Cat = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceCat_restructured/I-0', i45_dir=root_dir + '/icedataset/IceCat_restructured/I-45', i90_dir=root_dir + '/icedataset/IceCat_restructured/I-90', i135_dir=root_dir + '/icedataset/IceCat_restructured/I-135', s0_dir=root_dir + '/icedataset/IceCat_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceCat_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceCat_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceCat_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceCat_restructured/masks', label_dir=root_dir + '/icedataset/IceCat_restructured/normals-png', transform=augs_train)
    dataset_Apple = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceApple_restructured/I-0', i45_dir=root_dir + '/icedataset/IceApple_restructured/I-45', i90_dir=root_dir + '/icedataset/IceApple_restructured/I-90', i135_dir=root_dir + '/icedataset/IceApple_restructured/I-135', s0_dir=root_dir + '/icedataset/IceApple_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceApple_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceApple_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceApple_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceApple_restructured/masks', label_dir=root_dir + '/icedataset/IceApple_restructured/normals-png', transform=augs_train)
    dataset_IceMouse = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceMouse_restructured/I-0', i45_dir=root_dir + '/icedataset/IceMouse_restructured/I-45', i90_dir=root_dir + '/icedataset/IceMouse_restructured/I-90', i135_dir=root_dir + '/icedataset/IceMouse_restructured/I-135', s0_dir=root_dir + '/icedataset/IceMouse_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceMouse_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceMouse_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceMouse_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceMouse_restructured/masks', label_dir=root_dir + '/icedataset/IceMouse_restructured/normals-png', transform=augs_train)
    dataset_IceHemisphere = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceHemisphere_restructured/I-0', i45_dir=root_dir + '/icedataset/IceHemisphere_restructured/I-45', i90_dir=root_dir + '/icedataset/IceHemisphere_restructured/I-90', i135_dir=root_dir + '/icedataset/IceHemisphere_restructured/I-135', s0_dir=root_dir + '/icedataset/IceHemisphere_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceHemisphere_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceHemisphere_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceHemisphere_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceHemisphere_restructured/masks', label_dir=root_dir + '/icedataset/IceHemisphere_restructured/normals-png', transform=augs_train)
    dataset_IceRabbit2 = IcesfpDataset(i0_dir=root_dir + '/icedataset/IceRabbit2_restructured/I-0', i45_dir=root_dir + '/icedataset/IceRabbit2_restructured/I-45', i90_dir=root_dir + '/icedataset/IceRabbit2_restructured/I-90', i135_dir=root_dir + '/icedataset/IceRabbit2_restructured/I-135', s0_dir=root_dir + '/icedataset/IceRabbit2_restructured/I-sum', dolp_dir=root_dir + '/icedataset/IceRabbit2_restructured/params/DoLP', aolp_dir=root_dir + '/icedataset/IceRabbit2_restructured/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/IceRabbit2_restructured/synthesis-normals', mask_dir=root_dir + '/icedataset/IceRabbit2_restructured/masks', label_dir=root_dir + '/icedataset/IceRabbit2_restructured/normals-png', transform=augs_train)
    dataset_icekitten_syn = IcesfpDataset(i0_dir=root_dir + '/icedataset/ice_syn_kitten/I-0', i45_dir=root_dir + '/icedataset/ice_syn_kitten/I-45', i90_dir=root_dir + '/icedataset/ice_syn_kitten/I-90', i135_dir=root_dir + '/icedataset/ice_syn_kitten/I-135', s0_dir=root_dir + '/icedataset/ice_syn_kitten/I-sum', dolp_dir=root_dir + '/icedataset/ice_syn_kitten/params/DoLP', aolp_dir=root_dir + '/icedataset/ice_syn_kitten/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/ice_syn_kitten/synthesis-normals', mask_dir=root_dir + '/icedataset/ice_syn_kitten/masks', label_dir=root_dir + '/icedataset/ice_syn_kitten/normals-png', transform=augs_train)
    dataset_icehippo_syn = IcesfpDataset(i0_dir=root_dir + '/icedataset/ice_syn_hippo/I-0', i45_dir=root_dir + '/icedataset/ice_syn_hippo/I-45', i90_dir=root_dir + '/icedataset/ice_syn_hippo/I-90', i135_dir=root_dir + '/icedataset/ice_syn_hippo/I-135', s0_dir=root_dir + '/icedataset/ice_syn_hippo/I-sum', dolp_dir=root_dir + '/icedataset/ice_syn_hippo/params/DoLP', aolp_dir=root_dir + '/icedataset/ice_syn_hippo/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/ice_syn_hippo/synthesis-normals', mask_dir=root_dir + '/icedataset/ice_syn_hippo/masks', label_dir=root_dir + '/icedataset/ice_syn_hippo/normals-png', transform=augs_train)
    dataset_icebunny_syn = IcesfpDataset(i0_dir=root_dir + '/icedataset/ice_syn_bunny/I-0', i45_dir=root_dir + '/icedataset/ice_syn_bunny/I-45', i90_dir=root_dir + '/icedataset/ice_syn_bunny/I-90', i135_dir=root_dir + '/icedataset/ice_syn_bunny/I-135', s0_dir=root_dir + '/icedataset/ice_syn_bunny/I-sum', dolp_dir=root_dir + '/icedataset/ice_syn_bunny/params/DoLP', aolp_dir=root_dir + '/icedataset/ice_syn_bunny/params/AoLP', synthesis_normals_dir=root_dir + '/icedataset/ice_syn_bunny/synthesis-normals', mask_dir=root_dir + '/icedataset/ice_syn_bunny/masks', label_dir=root_dir + '/icedataset/ice_syn_bunny/normals-png', transform=augs_train)
    db_list_ice = [dataset_icetiger, dataset_icebonze, dataset_icepixiu2, dataset_icecloud, dataset_icebird1, dataset_icebird3, dataset_Mount, dataset_icepixiu, dataset_SunshineDoll, dataset_Cat, dataset_icerabbit1]
    db_train_list = db_list_ice
    dataset = torch.utils.data.ConcatDataset(db_train_list)
    trainLoader = DataLoader(dataset, num_workers=num_workers, batch_size=batch_size, drop_last=True, pin_memory=pin_memory)
    testLoader_dataset_iceapple = DataLoader(dataset_Apple, batch_size=1, num_workers=num_workers, drop_last=True, pin_memory=pin_memory)
    testLoader_dataset_icebird2 = DataLoader(dataset_icebird2, batch_size=1, num_workers=num_workers, drop_last=True, pin_memory=pin_memory)
    testLoader_dataset_iceMouse = DataLoader(dataset_IceMouse, batch_size=1, num_workers=num_workers, drop_last=True, pin_memory=pin_memory)
    testLoader_dataset_iceHemisphere = DataLoader(dataset_IceHemisphere, batch_size=1, num_workers=num_workers, drop_last=True, pin_memory=pin_memory)
    testLoader_dataset_iceRabbit2 = DataLoader(dataset_IceRabbit2, batch_size=1, num_workers=num_workers, drop_last=True, pin_memory=pin_memory)
    print('trainLoader size:', trainLoader.__len__() * trainLoader.batch_size)
    return (trainLoader, testLoader_dataset_iceapple, testLoader_dataset_icebird2, testLoader_dataset_iceMouse, testLoader_dataset_iceHemisphere, testLoader_dataset_iceRabbit2)
